

public class Constants {

	public static final String iAccountPassword = "Absnet4$";
	public static final String oAccountLock = "div.login-block > div";
	public static final String iActive = "active";
	public static final String oOption = "option";
	public static final String hexDecimalRed = "#ff";
	public static final String hexDecimalGreen = "#008000";
	public static final String hexDecimalWhite = "#008000";
	public static final String hexDecimalGrey = "#008000";
	public static final String hexDecimalYellow = "#008000";
	public static final String hexDecimalOrange = "#008000";
	public static final String hexDecimalLightBlue = "#008000";
	public static final String hexDecimalDarkBlue = "#008000";
	public static final String Date1 = "MMM-yyyy";
	public static final String Date2 = "MMM-dd-yyyy";
	public static final String Date3 = "ddhhmmss";
	public static final String oTxtFilter = "txtFilter";
	public static final String iAccept = "Accept";
	public static final String iDismiss = "Dismiss";
	public static final String sSubmissionTable = "SubmissionTable";
	public static final String sSubmissionTableDeal1 = "SubmissionTableDeal1";
	public static final String oTableView = "tableview";
	public static final String sGridAssetClassList = "GridAssetClassList";
	public static final String iUser = "AutoTest_";
	public static final String iPasswordReminder = "Password Reminder";
	public static final String iAccountCreated = "Account created";
	public static final String oListGrid = "//div[@id='tableViewList']/div";
	public static final String osearchDealinGridView2 = "/div";
	public static final String osearchDealinGridView3 = "/div[";
	public static final String osearchDealinGridView4 = "]";
	public static final String osearchDealinGridView5 = "//div[@id='";
	public static final String osearchDealinGridView6 = "']";
	public static final String osearchDealinGridView7 = "/div/a/div/h3";
	public static final String osearchDealinGridView8 = "//div[@id='";
	public static final String osearchDealinGridView9 = "']/div/div[";
	public static final String osearchDealinGridView10 = "]/a/div/h3";
	public static final String oGridView = "/div/a/div";
	public static final String oGridView1 = "]/a/div";
	public static final String header = "h3";
	public static final String oDeal1 = "//div[";
	public static final String oDeal2 = "]/div/div/ul";
	public static final String oDeal3 = "]/div/h3/span/a/img";
	public static final String iDatabaseName = "jdbc:sqlserver://LDC-WGRRQADB301:1433;databaseName=";
	public static final String iDriverName = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
	public static final String iDBUsername = "membadmin";
	public static final String iDBPassword = "password";
	public static final String sHome="HomePage";
	public static final String oHomeButton="HomeButton";
	public static final String iHomeButtonValue="moveToElement-***";
	public static final String oNavigationList="NavigationList";
	public static final String otr="tr";
	public static final String otd="td";
	public static final String olabel="label";
	public static final String oinput="input";
	public static final String olistViewList="listViewList";
	public static final String olink="a";
	public static final String oPaginationContainer="//div[@class='pagination-container']/ul";
	public static final String oListViewTr="//div[@id='listViewList']/table/tbody/tr[";
	public static final String oListViewTd="]/td/a/span";
	public static final String oSortByOption1="//div/div/div/div/ul/li/a";
	public static final String oSortByOption2="//div/div/div/div/ul/li[";
	public static final String oSortByOption3="]/a";
	public static final String otableViewList="tableViewList";
	public static final String osearchDealinGridView1="//div[@id='tableViewList']/div";
	public static final String osearchDealinGridView11="]//div[@class='btmrght']";
	public static final String osearchDealinGridView12="/";
	public static final String oPermissionHeader = "//*[@class='table-responsive']/table/thead";
	public static final String oPermissionRows = "//tr[2]/td[";
	public static final String oInput = "]/input";
	public static final String oAdminRole1 = "//div[@class='btn-group']/label[1]/input";
	public static final String oAdminRole2 = "//div[@class='btn-group']/label[2]/input";
	public static final String oSuccessMessage = "successMsg";
	public static final String oSubmitFiles1 = "//div[@class='uploadFile']//div[@class='row']";
	public static final String oSubmitFiles2 = "//div/div/form/div";
	public static final String oSubmitFilesHeader = "//div/form/div/h3";
	public static final String oYourTaskListElements = "//div[@id='tableViewList']/div/div";
	public static final String oYourTaskList1 = "//div[@id='tableViewList']/div/div/a/div";
	public static final String oYourTaskList2 = "//div[@id='tableViewList']/div/div/a/div/span[2]";
	public static final String oYourTaskList3 = "//div[@id='tableViewList']/div/div[";
	public static final String oYourTaskList4 = "]/a/div/span[2]";
	public static final String oMUHeader = "//th/a";
	public static final String oMUHeader1 = "//th[";
	public static final String oMUHeader2 = "]/a";
	public static final String oDueDates1 = "//div[@id='editduemodal']/div/div/div[";
	public static final String oDueDates2 = "]/div[2]/div/input";
	public static final String oDueDates3 = "//div[@id='dueDates']/div[3]/div/div[";
	public static final String oDueDates4 = "]/div/div[2]/span";
	public static final String oDueDatesRow = "//*[@class='row']";
	public static final String oItemizedUser1 = "//ul[@class='pagination']/li";
	public static final String oItemizedUser2 = "//table[@class='table']/tbody/tr";
	public static final String oItemizedUser3 = "]/td";
	public static final String oItemizedUser4 = "]/td[2]/a";
	public static final String oYTStatus = "//div[@id='listViewList']/table/tbody/tr[2]/td/a/span";
	public static final String oSubStatus = "//table[@id='submissionHistoryTable']/tbody/tr/td/span";
	public static final String oVintage="Vintage";
	public static final String oid="id";
	public static final String oPublished="Published";
	public static final String oSubmissionTable="SubmissionTable";
	public static final String otxtFilter="txtFilter";
	public static final String oListView1="//table[@id='listViewList']/tbody/tr[";
	public static final String oListView2="]/td[2]/a/span";	

}
